// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7G7sy0uSzwUyE23-hb9BFh7Bn-KgjztI',
    appId: '1:263476182469:web:b2e67c0df24b38ec651fac',
    messagingSenderId: '263476182469',
    projectId: 'transport-4b377',
    authDomain: 'transport-4b377.firebaseapp.com',
    databaseURL: 'https://transport-4b377-default-rtdb.firebaseio.com',
    storageBucket: 'transport-4b377.firebasestorage.app',
    measurementId: 'G-KZJ2WP641W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJPMnoZIDj1p9WlBH4FxSg3GTYVGyZxZY',
    appId: '1:263476182469:android:ddc5a77e0596c38b651fac',
    messagingSenderId: '263476182469',
    projectId: 'transport-4b377',
    databaseURL: 'https://transport-4b377-default-rtdb.firebaseio.com',
    storageBucket: 'transport-4b377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm7CYa5nRSSySzD95qnXngED29KxKw5w8',
    appId: '1:263476182469:ios:fd89ba6fa39c33dd651fac',
    messagingSenderId: '263476182469',
    projectId: 'transport-4b377',
    databaseURL: 'https://transport-4b377-default-rtdb.firebaseio.com',
    storageBucket: 'transport-4b377.firebasestorage.app',
    androidClientId: '263476182469-1160v8ibbqliedcnrbs2vkbs462b4rc1.apps.googleusercontent.com',
    iosClientId: '263476182469-k1352c2tm32n609a7lcocar0grq51h4i.apps.googleusercontent.com',
    iosBundleId: 'com.trasnport.dz.trasport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm7CYa5nRSSySzD95qnXngED29KxKw5w8',
    appId: '1:263476182469:ios:fd89ba6fa39c33dd651fac',
    messagingSenderId: '263476182469',
    projectId: 'transport-4b377',
    databaseURL: 'https://transport-4b377-default-rtdb.firebaseio.com',
    storageBucket: 'transport-4b377.firebasestorage.app',
    androidClientId: '263476182469-1160v8ibbqliedcnrbs2vkbs462b4rc1.apps.googleusercontent.com',
    iosClientId: '263476182469-k1352c2tm32n609a7lcocar0grq51h4i.apps.googleusercontent.com',
    iosBundleId: 'com.trasnport.dz.trasport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7G7sy0uSzwUyE23-hb9BFh7Bn-KgjztI',
    appId: '1:263476182469:web:a565db57f79bb715651fac',
    messagingSenderId: '263476182469',
    projectId: 'transport-4b377',
    authDomain: 'transport-4b377.firebaseapp.com',
    databaseURL: 'https://transport-4b377-default-rtdb.firebaseio.com',
    storageBucket: 'transport-4b377.firebasestorage.app',
    measurementId: 'G-F1EQTBHHY7',
  );

}